import React, { createContext, useState, useEffect } from 'react';

export const ThemeLanguageContext = createContext();

const translations = {
    en: {
        dashboard: "Dashboard",
        admin_console: "Admin Console",
        recent_meetings: "Recent Meetings",
        sign_out: "Sign Out",
        welcome: "Welcome",
        manage_meetings: "Manage your meetings and communication.",
        new_meeting: "New Meeting",
        start_instant: "Start an instant meeting with your team.",
        meeting_topic: "Meeting Topic (Optional)",
        start_meeting: "Start Meeting",
        starting: "Starting...",
        join_meeting: "Join Meeting",
        enter_code: "Enter a meeting code or link to join.",
        meeting_id_link: "Meeting ID or Link",
        join_now: "Join Now",
        schedule: "Schedule",
        plan_future: "Plan a meeting for a future date.",
        coming_soon: "Coming Soon",
        overview: "Overview",
        users: "Users",
        meetings: "Meetings",
        back_to_app: "Back to App",
        total_users: "Total Users",
        active_meetings: "Active Meetings",
        host_nodes: "Host Nodes",
        participants: "Participants",
        add_user: "Add User",
        name_email: "Name & Email",
        role: "Role",
        status: "Status",
        actions: "Actions",
        meeting_title_id: "Meeting Title & ID",
        host: "Host",
        date: "Date",
        welcome_back: "Welcome Back",
        network_email: "Email Address",
        security_key: "Password",
        initiate_login: "Sign In",
        join_as_guest: "Join as Guest",
        new_instance: "New Instance?",
        register_directory: "Register Directory",
        create_identity: "Create Identity",
        join_network: "Join the communication network",
        full_identity_name: "Full Name",
        register_node: "Register Node",
        already_registered: "Already Registered?",
        sign_in_protocol: "Sign In Protocol",
        profile: "Profile",
        save_changes: "Save Changes",
        // Auth specific
        login_title: "Log in to Account",
        register_title: "Create Account",
        remember_me: "Remember",
        forgot_password: "Forgot?",
        or_continue_with: "or continue with",
        social: "Social",
        guest_mode: "Guest Mode",
        hello_friend: "Hello, Friend!",
        welcome_back_title: "Welcome Back!",
        login_desc: "Enter your personal details and start your journey with us today.",
        register_desc: "To keep connected with us please login with your personal info.",
        accept_terms: "Accept Terms",
        home: "Home",
        back: "Back",
        enter_details: "Please enter your details",
        create_free_account: "Create your free account",
        // Toasts & confirms
        confirm_delete_meeting: "Are you sure you want to delete this meeting?",
        meeting_deleted: "Meeting deleted",
        action_failed: "Action failed",
        pw_required_private: "Password is required for private rooms",
        pw_not_allowed_public: "Public rooms cannot have password protection",
        // Password strength
        pw_weak: "Weak",
        pw_fair: "Fair",
        pw_good: "Good",
        pw_strong: "Strong",
        pw_min_6_chars: "At least 6 characters required",
        pw_too_weak: "Password too weak for private room",
        pw_copied: "Password copied to clipboard!",
        pw_requirement: "Must contain at least 2 of: uppercase, lowercase, digits",
        // Room events
        kicked_msg: "You have been removed from the meeting.",
        blocked_msg: "You have been permanently blocked from this meeting.",
        meeting_ended_msg: "Host has ended the meeting for everyone.",
        host_denied_share: "Host denied your request to share.",
        host_stopped_share: "Host has stopped your screen sharing.",
        meeting_not_found: "Meeting not found.",
        record_host_only: "Only the meeting host can record the meeting.",
        chat_disabled: "Chat is disabled for this room.",
        confirm_send_file: "Do you want to send this file?",
        confirm_delete_msg: "Are you sure you want to delete this message?",
        confirm_kick: "Are you sure you want to kick this user?",
        confirm_block: "Are you sure you want to BLOCK this user? They will not be able to rejoin.",
        confirm_end_meeting: "Are you sure you want to end the meeting for everyone?",
        confirm_guest_login: "Guests cannot perform this action. Would you like to log in or register?",
        // Bottom controls
        ctl_mute: "Mute",
        ctl_unmute: "Unmute",
        ctl_start_video: "Start Video",
        ctl_stop_video: "Stop Video",
        ctl_share: "Share",
        ctl_present_file: "File",
        ctl_present_file_full: "Present a file (PDF, Word, TXT, PPTX)",
        ctl_stop_share: "Stop",
        ctl_record: "Record",
        ctl_stop_record: "Stop",
        ctl_raise: "Raise",
        ctl_raise_hand: "Raise hand",
        ctl_settings: "Settings",
        ctl_chat: "Chat",
        ctl_chat_short: "Chat",
        ctl_people: "People",
        ctl_people_short: "People",
        ctl_leave: "Leave",
        ctl_more: "More",
        ctl_meeting_id: "Meeting ID",
        ctl_copied: "Copied!",
        ctl_share_screen: "Share screen",
        ctl_stop_sharing: "Stop sharing",
        ctl_start_recording: "Start recording",
        ctl_stop_recording: "Stop recording",
        ctl_unmute_hold: "Unmute (hold to talk)",
        // Leave dialog
        leave_confirm: "Leave the meeting?",
        leave_only_me: "Leave meeting",
        leave_only_me_sub: "Others can keep going",
        leave_end_all: "End for everyone",
        leave_end_all_sub: "Closes the room and removes everyone",
        // Participants panel
        find_participant: "Find participant...",
        you_label: "You",
        mute_everyone: "Mute Everyone",
        role_host: "Host",
        role_cohost: "Co-host",
        role_participant: "Participant",
        role_guest: "Guest",
        // Chat
        chat_empty_title: "No messages yet",
        chat_empty_sub: "Start the conversation!",
        chat_input_placeholder: "Type a message...",
        chat_input_edit_placeholder: "Edit message...",
        chat_close: "Close",
        chat_send: "Send",
        chat_edit: "Edit",
        chat_delete: "Delete",
        chat_attach: "Attach file",
        chat_download: "Download",
        chat_today: "Today",
        chat_send_hint: "Enter — send",
        // Screen share toasts
        share_unsupported: "This browser does not support screen sharing.",
        share_busy: "{name} is currently sharing the screen.",
        share_failed: "Could not start screen sharing.",
        // Admin page
        admin_nav_section: "Management",
        total_meetings: "Total Meetings",
        total_messages: "Total Messages",
        today_suffix: "today",
        public_label: "Public",
        private_label: "Private",
        admins: "Admins",
        guests: "Guests",
        blocked: "Blocked",
        unblocked: "Active",
        today_activity: "Today Activity",
        users_growth: "User Growth",
        meetings_growth: "Meeting Growth",
        activity_chart: "Activity Chart",
        chart_subtitle: "New users and meetings over time",
        user_roles: "User Roles",
        meeting_types: "Meeting Types",
        search_user: "Search by name or email...",
        all_roles: "All Roles",
        all_status: "All Status",
        all_types: "All Types",
        n_results: "results",
        user_col: "User",
        type_col: "Type",
        edit_action: "Edit",
        block_action: "Block",
        unblock_action: "Unblock",
        delete_action: "Delete",
        no_users_found: "No users found.",
        no_meetings_found: "No meetings found.",
        active_status: "Active",
        completed_status: "Completed",
        scheduled_status: "Scheduled",
        full_name: "Full Name",
        password_label: "Password",
        password_edit_hint: "Password (leave blank to keep unchanged)",
        save_btn: "Save",
        create_btn: "Create",
        edit_user: "Edit User",
        name_placeholder: "Full Name",
        last_days_prefix: "Last",
        last_days_suffix: "days",
        total_n: "Total",
        selected: "selected",
        clear: "Clear",
        retry: "Retry",
        error_load: "Failed to load data.",
        export_csv: "Export CSV",
        search_meeting: "Search by title or code...",
        user_deleted: "User deleted",
        user_created: "User created",
        user_updated: "User updated",
        role_updated: "Role updated",
        action_done: "Done",
        confirm_delete_user: "Are you sure you want to delete user",
        confirm_bulk_delete: "Delete the selected users?",
        confirm_bulk_block: "Block the selected users?",
        confirm_bulk_unblock: "Unblock the selected users?",
        // 404 page
        page_not_found: "Page Not Found",
        notfound_title: "404",
        notfound_desc: "Sorry, the page you're looking for doesn't exist.",
        notfound_btn: "Go Home",
        // Guest features
        guest_meeting_created: "Meeting created! Register to save & access history.",
        guest_register_now: "Register",
        // Misc
        cancel: "Cancel",
    },
    uz: {
        dashboard: "Boshqaruv paneli",
        admin_console: "Admin panel",
        recent_meetings: "So'nggi uchrashuvlar",
        sign_out: "Chiqish",
        welcome: "Xush kelibsiz",
        manage_meetings: "Uchrashuv va muloqotlarni boshqaring.",
        new_meeting: "Yangi uchrashuv",
        start_instant: "Jamoangiz bilan tezkor uchrashuv boshlash.",
        meeting_topic: "Uchrashuv mavzusi (Ixtiyoriy)",
        start_meeting: "Boshlash",
        starting: "Boshlanmoqda...",
        join_meeting: "Uchrashuvga qo'shilish",
        enter_code: "Qo'shilish uchun kod yoki havolani kiriting.",
        meeting_id_link: "ID yoki Havola",
        join_now: "Qo'shilish",
        schedule: "Rejalashtirish",
        plan_future: "Kelajakdagi uchrashuvni rejalashtirish.",
        coming_soon: "Tez orada",
        overview: "Umumiy",
        users: "Foydalanuvchilar",
        meetings: "Uchrashuvlar",
        back_to_app: "Ilovaga qaytish",
        total_users: "Jami foydalanuvchilar",
        active_meetings: "Faol uchrashuvlar",
        host_nodes: "Xostlar",
        participants: "Ishtirokchilar",
        add_user: "Foydalanuvchi qo'shish",
        name_email: "Ism va Email",
        role: "Rol",
        status: "Holat",
        actions: "Harakatlar",
        meeting_title_id: "Uchrashuv nomi & ID",
        host: "Xost",
        date: "Sana",
        welcome_back: "Xush kelibsiz",
        network_email: "Email manzil",
        security_key: "Parol",
        initiate_login: "Kirish",
        join_as_guest: "Mehmon bo'lib qo'shilish",
        new_instance: "Ro'yxatdan o'tmaganmisiz?",
        register_directory: "Ro'yxatdan o'tish",
        create_identity: "Hisob yaratish",
        join_network: "Muloqot tarmog'iga qo'shiling",
        full_identity_name: "To'liq ism",
        register_node: "Ro'yxatdan o'tish",
        already_registered: "Hisobingiz bormi?",
        sign_in_protocol: "Kirish",
        profile: "Profil",
        save_changes: "Saqlash",
        // Auth specific
        login_title: "Tizimga kirish",
        register_title: "Hisob yaratish",
        remember_me: "Eslab qolish",
        forgot_password: "Unutdingizmi?",
        or_continue_with: "yoki davom eting",
        social: "Ijtimoiy",
        guest_mode: "Mehmon rejimi",
        hello_friend: "Salom, do'stim!",
        welcome_back_title: "Xush kelibsiz!",
        login_desc: "Shaxsiy ma'lumotlaringizni kiriting va bugun biz bilan sayohatingizni boshlang.",
        register_desc: "Biz bilan bog'lanib turish uchun shaxsiy ma'lumotlaringiz orqali kiring.",
        accept_terms: "Shartlarga roziman",
        home: "Bosh sahifa",
        back: "Orqaga",
        enter_details: "Ma'lumotlarni kiriting",
        create_free_account: "Bepul hisob yarating",
        confirm_delete_meeting: "Ushbu uchrashuvni o'chirmoqchimisiz?",
        meeting_deleted: "Uchrashuv o'chirildi",
        action_failed: "Amal bajarilmadi",
        pw_required_private: "Shaxsiy xonalar uchun parol kerak",
        pw_not_allowed_public: "Ommaviy xonalar parol bilan himoyalanmaydi",
        pw_weak: "Zaif",
        pw_fair: "O'rtacha",
        pw_good: "Yaxshi",
        pw_strong: "Kuchli",
        pw_min_6_chars: "Kamida 6 ta belgi kerak",
        pw_too_weak: "Parol shaxsiy xona uchun juda zaif",
        pw_copied: "Parol nusxaga ko'chirildi!",
        pw_requirement: "Kamida 2 ta: bosh harf, kichik harf, raqam o'z ichiga olishi kerak",
        kicked_msg: "Siz uchrashuvdan chiqarib yuborildingiz.",
        blocked_msg: "Siz bu uchrashuvdan doimiy ravishda bloklangansiz.",
        meeting_ended_msg: "Xost uchrashuv tugundi.",
        host_denied_share: "Xost ulashish so'rovingizni rad etdi.",
        host_stopped_share: "Xost ekran ulashishingizni to'xtatdi.",
        meeting_not_found: "Uchrashuv topilmadi.",
        record_host_only: "Faqat xost yozib olishi mumkin.",
        chat_disabled: "Ushbu xonada chat o'chirib qo'yilgan.",
        confirm_send_file: "Bu faylni yubormoqchimisiz?",
        confirm_delete_msg: "Bu xabarni o'chirmoqchimisiz?",
        confirm_kick: "Bu foydalanuvchini chiqarib yubormoqchimisiz?",
        confirm_block: "Bu foydalanuvchini bloklaysizmi? Ular qayta kira olmaydi.",
        confirm_end_meeting: "Barcha uchun uchrashuvni tugatmoqchimisiz?",
        confirm_guest_login: "Mehmonlar bu amalni bajara olmaydi. Tizimga kirmoqchimisiz?",
        ctl_mute: "Mikrofonni o'chir",
        ctl_unmute: "Yoqish",
        ctl_start_video: "Kamerani yoq",
        ctl_stop_video: "Kamerani o'chir",
        ctl_share: "Ulashish",
        ctl_present_file: "Fayl",
        ctl_present_file_full: "Fayl taqdimoti (PDF, Word, TXT, PPTX)",
        ctl_stop_share: "To'xtatish",
        ctl_record: "Yozib olish",
        ctl_stop_record: "To'xtatish",
        ctl_raise: "Qo'l",
        ctl_raise_hand: "Qo'l ko'tarish",
        ctl_settings: "Sozlamalar",
        ctl_chat: "Chat",
        ctl_chat_short: "Chat",
        ctl_people: "Ishtirokchilar",
        ctl_people_short: "Odamlar",
        ctl_leave: "Chiqish",
        ctl_more: "Yana",
        ctl_meeting_id: "Uchrashuv ID",
        ctl_copied: "Nusxalandi!",
        ctl_share_screen: "Ekran ulashish",
        ctl_stop_sharing: "Ulashishni to'xtatish",
        ctl_start_recording: "Yozib olishni boshlash",
        ctl_stop_recording: "Yozib olishni to'xtatish",
        ctl_unmute_hold: "Yoqish (ushlab gapiring)",
        leave_confirm: "Xonadan chiqasizmi?",
        leave_only_me: "Faqat o'zim chiqaman",
        leave_only_me_sub: "Boshqalar davom ettira oladi",
        leave_end_all: "Hammaga tugatish",
        leave_end_all_sub: "Xonani yopadi va barchani chiqaradi",
        find_participant: "Ishtirokchi qidirish...",
        you_label: "Siz",
        mute_everyone: "Hammani o'chirish",
        role_host: "Xost",
        role_cohost: "Hammuallif",
        role_participant: "Ishtirokchi",
        role_guest: "Mehmon",
        chat_empty_title: "Hali xabar yo'q",
        chat_empty_sub: "Jamoangiz bilan muloqotni boshlang!",
        chat_input_placeholder: "Xabar yozing...",
        chat_input_edit_placeholder: "Xabarni tahrirlang...",
        chat_close: "Yopish",
        chat_send: "Yuborish",
        chat_edit: "Tahrirlash",
        chat_delete: "O'chirish",
        chat_attach: "Fayl biriktirish",
        chat_download: "Yuklab olish",
        chat_today: "Bugun",
        chat_send_hint: "Enter — yuborish",
        share_unsupported: "Bu brauzer ekran ulashishni qo'llab-quvvatlamaydi.",
        share_busy: "{name} hozir ekranini ulashmoqda.",
        share_failed: "Ekran ulashishni boshlab bo'lmadi.",
        cancel: "Bekor",
        // Admin page
        admin_nav_section: "Boshqaruv",
        total_meetings: "Jami uchrashuvlar",
        total_messages: "Jami xabarlar",
        today_suffix: "bugun",
        public_label: "Ommaviy",
        private_label: "Shaxsiy",
        admins: "Adminlar",
        guests: "Mehmonlar",
        blocked: "Bloklangan",
        unblocked: "Faol",
        today_activity: "Bugun aktivlik",
        users_growth: "Foydalanuvchilar o'sishi",
        meetings_growth: "Uchrashuvlar o'sishi",
        activity_chart: "Faollik grafigi",
        chart_subtitle: "Yangi foydalanuvchilar va uchrashuvlar soni",
        user_roles: "Foydalanuvchi rollari",
        meeting_types: "Uchrashuv turlari",
        search_user: "Ism yoki email qidirish...",
        all_roles: "Barcha rollar",
        all_status: "Barcha holat",
        all_types: "Barcha tur",
        n_results: "ta natija",
        user_col: "Foydalanuvchi",
        type_col: "Tur",
        edit_action: "Tahrirlash",
        block_action: "Bloklash",
        unblock_action: "Ochish",
        delete_action: "O'chirish",
        no_users_found: "Foydalanuvchilar topilmadi.",
        no_meetings_found: "Uchrashuvlar topilmadi.",
        active_status: "Faol",
        completed_status: "Tugagan",
        scheduled_status: "Rejalashtirilgan",
        full_name: "To'liq ism",
        password_label: "Parol",
        password_edit_hint: "Parol (o'zgartirmaslik uchun bo'sh qoldiring)",
        save_btn: "Saqlash",
        create_btn: "Yaratish",
        edit_user: "Foydalanuvchini tahrirlash",
        name_placeholder: "Ism Familiya",
        last_days_prefix: "So'nggi",
        last_days_suffix: "kun",
        total_n: "Jami",
        selected: "tanlandi",
        clear: "Tozalash",
        retry: "Qayta urinish",
        error_load: "Ma'lumotni yuklab bo'lmadi.",
        export_csv: "CSV yuklab olish",
        search_meeting: "Sarlavha yoki kod bo'yicha qidirish...",
        user_deleted: "Foydalanuvchi o'chirildi",
        user_created: "Foydalanuvchi yaratildi",
        user_updated: "Foydalanuvchi yangilandi",
        role_updated: "Rol yangilandi",
        action_done: "Bajarildi",
        confirm_delete_user: "Foydalanuvchini o'chirmoqchimisiz",
        confirm_bulk_delete: "Tanlangan foydalanuvchilar o'chirilsinmi?",
        confirm_bulk_block: "Tanlangan foydalanuvchilar bloklansinmi?",
        confirm_bulk_unblock: "Tanlangan foydalanuvchilar blokdan chiqarilsinmi?",
        // 404 page
        page_not_found: "Sahifa topilmadi",
        notfound_title: "404",
        notfound_desc: "Kechirasiz, siz qidirayotgan sahifa mavjud emas.",
        notfound_btn: "Bosh sahifaga",
        // Guest features
        guest_meeting_created: "Uchrashuv yaratildi! Tarixini saqlash uchun ro'yxatdan o'ting.",
        guest_register_now: "Ro'yxatdan o'tish",
    },
    ru: {
        dashboard: "Панель управления",
        admin_console: "Консоль админа",
        recent_meetings: "Недавние встречи",
        sign_out: "Выйти",
        welcome: "Добро пожаловать",
        manage_meetings: "Управляйте встречами и общением.",
        new_meeting: "Новая встреча",
        start_instant: "Начать мгновенную встречу с командой.",
        meeting_topic: "Тема встречи (Необязательно)",
        start_meeting: "Начать встречу",
        starting: "Запуск...",
        join_meeting: "Присоединиться",
        enter_code: "Введите код или ссылку для подключения.",
        meeting_id_link: "ID встречи или ссылка",
        join_now: "Присоединиться",
        schedule: "Запланировать",
        plan_future: "Запланировать встречу на будущее.",
        coming_soon: "Скоро",
        overview: "Обзор",
        users: "Пользователи",
        meetings: "Встречи",
        back_to_app: "Вернуться в приложение",
        total_users: "Всего пользователей",
        active_meetings: "Активные встречи",
        host_nodes: "Организаторы",
        participants: "Участники",
        add_user: "Добавить",
        name_email: "Имя и Email",
        role: "Роль",
        status: "Статус",
        actions: "Действия",
        meeting_title_id: "Название & ID",
        host: "Организатор",
        date: "Дата",
        welcome_back: "С возвращением",
        network_email: "Электронная почта",
        security_key: "Пароль",
        initiate_login: "Войти",
        join_as_guest: "Войти как гость",
        new_instance: "Нет аккаунта?",
        register_directory: "Зарегистрироваться",
        create_identity: "Создать аккаунт",
        join_network: "Присоединяйтесь к сети",
        full_identity_name: "Полное имя",
        register_node: "Зарегистрироваться",
        already_registered: "Уже есть аккаунт?",
        sign_in_protocol: "Войти",
        profile: "Профиль",
        save_changes: "Сохранить изменения",
        // Auth specific
        login_title: "Вход в аккаунт",
        register_title: "Создать аккаунт",
        remember_me: "Запомнить",
        forgot_password: "Забыли?",
        or_continue_with: "или продолжить через",
        social: "Соцсети",
        guest_mode: "Гостевой режим",
        hello_friend: "Привет, друг!",
        welcome_back_title: "С возвращением!",
        login_desc: "Введите свои данные и начните путешествие с нами сегодня.",
        register_desc: "Чтобы оставаться на связи, пожалуйста, войдите под своими данными.",
        accept_terms: "Принимаю условия",
        home: "Главная",
        back: "Назад",
        enter_details: "Введите свои данные",
        create_free_account: "Создайте бесплатный аккаунт",
        confirm_delete_meeting: "Вы уверены, что хотите удалить эту встречу?",
        meeting_deleted: "Встреча удалена",
        action_failed: "Действие не выполнено",
        pw_required_private: "Для приватных комнат требуется пароль",
        pw_not_allowed_public: "Публичные комнаты не должны быть защищены паролем",
        pw_weak: "Слабый",
        pw_fair: "Средний",
        pw_good: "Хороший",
        pw_strong: "Сильный",
        pw_min_6_chars: "Требуется не менее 6 символов",
        pw_too_weak: "Пароль слишком слаб для приватной комнаты",
        pw_copied: "Пароль скопирован в буфер обмена!",
        pw_requirement: "Должен содержать как минимум 2 из: прописные, строчные, цифры",
        kicked_msg: "Вас удалили из встречи.",
        blocked_msg: "Вы навсегда заблокированы в этой встрече.",
        meeting_ended_msg: "Организатор завершил встречу.",
        host_denied_share: "Организатор отклонил ваш запрос на демонстрацию.",
        host_stopped_share: "Организатор остановил вашу демонстрацию экрана.",
        meeting_not_found: "Встреча не найдена.",
        record_host_only: "Только организатор может записывать встречу.",
        chat_disabled: "Чат отключён в этой комнате.",
        confirm_send_file: "Вы хотите отправить этот файл?",
        confirm_delete_msg: "Вы уверены, что хотите удалить это сообщение?",
        confirm_kick: "Вы уверены, что хотите выгнать этого пользователя?",
        confirm_block: "Заблокировать этого пользователя? Он не сможет вернуться.",
        confirm_end_meeting: "Завершить встречу для всех?",
        confirm_guest_login: "Гости не могут выполнять это действие. Хотите войти или зарегистрироваться?",
        ctl_mute: "Выкл. микрофон",
        ctl_unmute: "Включить",
        ctl_start_video: "Включить видео",
        ctl_stop_video: "Выкл. видео",
        ctl_share: "Демонстрация",
        ctl_present_file: "Файл",
        ctl_present_file_full: "Презентация файла (PDF, Word, TXT, PPTX)",
        ctl_stop_share: "Остановить",
        ctl_record: "Запись",
        ctl_stop_record: "Стоп",
        ctl_raise: "Рука",
        ctl_raise_hand: "Поднять руку",
        ctl_settings: "Настройки",
        ctl_chat: "Чат",
        ctl_chat_short: "Чат",
        ctl_people: "Участники",
        ctl_people_short: "Люди",
        ctl_leave: "Выйти",
        ctl_more: "Ещё",
        ctl_meeting_id: "ID встречи",
        ctl_copied: "Скопировано!",
        ctl_share_screen: "Демонстрация экрана",
        ctl_stop_sharing: "Остановить демонстрацию",
        ctl_start_recording: "Начать запись",
        ctl_stop_recording: "Остановить запись",
        ctl_unmute_hold: "Включить (удерживайте)",
        leave_confirm: "Выйти из встречи?",
        leave_only_me: "Выйти только мне",
        leave_only_me_sub: "Другие смогут продолжить",
        leave_end_all: "Завершить для всех",
        leave_end_all_sub: "Закроет комнату для всех",
        find_participant: "Найти участника...",
        you_label: "Вы",
        mute_everyone: "Выключить у всех",
        role_host: "Организатор",
        role_cohost: "Соорганизатор",
        role_participant: "Участник",
        role_guest: "Гость",
        chat_empty_title: "Сообщений пока нет",
        chat_empty_sub: "Начните общение с командой!",
        chat_input_placeholder: "Напишите сообщение...",
        chat_input_edit_placeholder: "Редактировать сообщение...",
        chat_close: "Закрыть",
        chat_send: "Отправить",
        chat_edit: "Редактировать",
        chat_delete: "Удалить",
        chat_attach: "Прикрепить файл",
        chat_download: "Скачать",
        chat_today: "Сегодня",
        chat_send_hint: "Enter — отправить",
        share_unsupported: "Этот браузер не поддерживает демонстрацию экрана.",
        share_busy: "{name} сейчас демонстрирует экран.",
        share_failed: "Не удалось начать демонстрацию.",
        cancel: "Отмена",
        // Admin page
        admin_nav_section: "Управление",
        total_meetings: "Всего встреч",
        total_messages: "Всего сообщений",
        today_suffix: "сегодня",
        public_label: "Публичная",
        private_label: "Приватная",
        admins: "Администраторы",
        guests: "Гости",
        blocked: "Заблокирован",
        unblocked: "Активен",
        today_activity: "Активность сегодня",
        users_growth: "Рост пользователей",
        meetings_growth: "Рост встреч",
        activity_chart: "График активности",
        chart_subtitle: "Новые пользователи и встречи за период",
        user_roles: "Роли пользователей",
        meeting_types: "Типы встреч",
        search_user: "Поиск по имени или email...",
        all_roles: "Все роли",
        all_status: "Все статусы",
        all_types: "Все типы",
        n_results: "результатов",
        user_col: "Пользователь",
        type_col: "Тип",
        edit_action: "Изменить",
        block_action: "Заблокировать",
        unblock_action: "Разблокировать",
        delete_action: "Удалить",
        no_users_found: "Пользователи не найдены.",
        no_meetings_found: "Встречи не найдены.",
        active_status: "Активна",
        completed_status: "Завершена",
        scheduled_status: "Запланирована",
        full_name: "Полное имя",
        password_label: "Пароль",
        password_edit_hint: "Пароль (оставьте пустым, чтобы не менять)",
        save_btn: "Сохранить",
        create_btn: "Создать",
        edit_user: "Редактировать пользователя",
        name_placeholder: "Имя Фамилия",
        last_days_prefix: "Последние",
        last_days_suffix: "дней",
        total_n: "Итого",
        selected: "выбрано",
        clear: "Очистить",
        retry: "Повторить",
        error_load: "Не удалось загрузить данные.",
        export_csv: "Экспорт CSV",
        search_meeting: "Поиск по названию или коду...",
        user_deleted: "Пользователь удалён",
        user_created: "Пользователь создан",
        user_updated: "Пользователь обновлён",
        role_updated: "Роль обновлена",
        action_done: "Готово",
        confirm_delete_user: "Удалить пользователя",
        confirm_bulk_delete: "Удалить выбранных пользователей?",
        confirm_bulk_block: "Заблокировать выбранных пользователей?",
        confirm_bulk_unblock: "Разблокировать выбранных пользователей?",
        // 404 page
        page_not_found: "Страница не найдена",
        notfound_title: "404",
        notfound_desc: "Извините, страница, которую вы ищете, не существует.",
        notfound_btn: "На главную",
        // Guest features
        guest_meeting_created: "Встреча создана! Зарегистрируйтесь, чтобы сохранить и просмотреть историю.",
        guest_register_now: "Зарегистрироваться",
    }
};

export const ThemeLanguageProvider = ({ children }) => {
    const [theme, setTheme] = useState(localStorage.getItem('theme') || 'light');
    const [lang, setLang] = useState(localStorage.getItem('lang') || 'uz');

    useEffect(() => {
        if (theme === 'dark') {
            document.documentElement.classList.add('dark');
        } else {
            document.documentElement.classList.remove('dark');
        }
        localStorage.setItem('theme', theme);
    }, [theme]);

    useEffect(() => {
        localStorage.setItem('lang', lang);
    }, [lang]);

    const toggleTheme = () => {
        setTheme(prev => prev === 'dark' ? 'light' : 'dark');
    };

    const changeLanguage = (newLang) => {
        setLang(newLang);
    };

    const t = (key) => {
        return translations[lang]?.[key] || translations['en'][key] || key;
    };

    return (
        <ThemeLanguageContext.Provider value={{ theme, toggleTheme, lang, changeLanguage, t }}>
            {children}
        </ThemeLanguageContext.Provider>
    );
};
